apiVersion: v1
kind: Service
metadata:
  name: ma-pagamento-service
spec:
  selector:
    app: ms-produto-selector
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8091
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8091
  type: LoadBalancer