apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-pedido
spec:
  selector:
    app: mongodb-pedido
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None